# no more versions needed! Compose spec supports all features w/o a version

services:

  # httpd:
  #   image: httpd
  #   labels:
  #     traefik.enable: true
  #     traefik.http.routers.httpd.rule: Host(`httpd.bret.lol`)
  #     traefik.http.routers.httpd.entrypoints: websecure
  #     traefik.http.routers.httpd.tls: true
  #   depends_on:
  #     traefik:
  #       condition: service_healthy

  portainer:
    image: registry-c25ea8a2dc-exchnage.apps.ir-central1.arvancaas.ir/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - 10000:9000
    labels:
      traefik.enable: true
      traefik.http.routers.portainer.rule: Host(`portainer.payhubix.io`)
      traefik.http.routers.portainer.entrypoints: websecure
      traefik.http.routers.portainer.tls: true

  nginx:
    image: nginx
    labels:
      traefik.enable: true
      traefik.http.routers.nginx.rule: Host(`nginx.payhubix.io`)
      traefik.http.routers.nginx.entrypoints: websecure
      traefik.http.routers.nginx.tls: true
    depends_on:
      traefik:
        condition: service_healthy

  traefik:
    image: "traefik:2.9"
    healthcheck:
      test: 
        - CMD
        - traefik
        - healthcheck
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      - ~/.certs/:/certs/
      - /var/run/docker.sock:/var/run/docker.sock

